### ISSUE TITLE
Switch to JSON-RPC as de facto provider implementation

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#173]
Full node fee estimation has just been implemented by `pathfinder`: https://github.com/eqlabs/pathfinder/pull/388

Now the full node JSON-RPC implementation has everything we need to implement a transaction sender. We should probably move away from the sequencer gateway.

Only one problem: due to the lack of a decentralized mempool, currently all the write methods are just proxied to the sequencer gateway. Therefore, if a full node is used by many people at the same time, you're more likely to get rate limited than just going to the sequencer yourself.

Should we wait for the mempool be become available (which will take some very long time I guess)? Or do we just do it anyways? Or do we take a hybird approach, where all the write methods are sent directly to the sequencer (probably with an option to go thru JSON-RPC instead anyways)?

**Comment by bbrandtom** [comment]
This is only an issue if you use an API provider (e.g. Chainstack) right? Running a local node should not have this problem

**Comment by xJonathanLEI** [comment]
Yes you're right. I guess with Infura coming into the field they should be able to properly handle the rate limit issue anyways (maybe getting whitelisted by StarkWare idk). By then even those using public RPC should be fine.

Personally I would really love to see JSONRPC becoming the defacto way of interacting with StarkNet. There are just still a few issues out there, including handling of pending state. Hope they get resolved sooner.

**Comment by xJonathanLEI** [comment]
`JsonRpcClient` now partially implements the `Provider` trait (#291). It's now possible to use JSON-RPC for account operations. This will power all wallet-related commands in [starkli](https://github.com/xJonathanLEI/starkli).

The current solution rather is a compromise. Eventually I'd like to have the `Provider` trait modeled after the JSON-RPC specs and make it the other way around - `SequencerGatewayProvider` will have to map its types to implement the new `Provider` trait, as much as it's possible to do.

**Comment by xJonathanLEI** [comment]
Finally started working on this now. This will be a huge PR will tons of breaking changes. I'd like to avoid breaking downstream applications whenever possible, but not much I can do to help with this one, and we have to get this one through as the whole ecosystem is moving towards JSON-RPC.

To make things easier, the current `SequencerGatewayProvider` will also implement the new, updated `Provider` trait, pretending itself to be a JSON-RPC backend, in the same way of how the JSON-RPC client pretends it's a sequencer backend today.
