### ISSUE TITLE
why is there not getter for fields in `SingleOwnerAccount` ?

### ISSUE THREAD

**Issue by tdelabro** [xJonathanLEI/starknet-rs#175]
I have a function that call a specific smart contract, I want to pass a SingleOwnerAccount as argument.

```rust
fn call_contract(
	account: SingleOwnerAccount<SequencerGatewayProvider, LocalWallet>
) {
      let contract_address = <some_address>
      let result = account
		.execute(&[Call {
			to: contract_address,
			selector: get_selector_from_name("mint").unwrap(),
			calldata: vec![
				account.address(),
				FieldElement::from_dec_str("1000000000000000000000").unwrap(),
				FieldElement::ZERO,
			],
		}])
		.send()
		.await
		.unwrap();
}
```

I want to use `miner_account.address()` as the first argument of the calldata.
Why is there no getters implemented onto  `SingleOwnerAccount` ?

Is it by design ? Or should I do a PR adding those getter methods ?

**Comment by xJonathanLEI** [comment]
You're right we should have that on the `Account` trait.

BTW you can use the `selector!` and `felt!` macros to avoid the `unwrap()` calls :)

**Comment by xJonathanLEI** [comment]
@tdelabro A new method `address()` has been added.
