### ISSUE TITLE
call contract `view` methods

### ISSUE THREAD

**Issue by tdelabro** [xJonathanLEI/starknet-rs#177]
How do I make a call to a `view` (read only) method of a contract?

I feel I have to use `Provider::call_contract`, but it require `signature` and `max_fee` as the two last arguments, which doesn't make sense when calling a `view`. 
Should I still use `call_contract` with and empty `Vec` as signature and 0 as max_fee, or is there a better way to do this ?

**Comment by xJonathanLEI** [comment]
It's not entirely true that `signature` and `max_fee` are meaningless for `call_contract` requests. Imagine trying to call a contract that reads the caller address, which forces your call to go through an account. And for your call to not get aborted, you need valid signatures. A similar issue exists when doing `estimate_fee`.

There has been an on-going discussion on the best approach to be taken here. But in any case that's up to StarkWare and the account contract implementors to decide. Not much can be done from our side.

And yes, you'll need to supply an empty `Vec` and zero `max_fee` if you're not going through an account contract.

Closing this optimistically. Please feel free to re-open if needed.

**Comment by tdelabro** [comment]
Thanks a lot for the explainations, I will do as advised !
