### ISSUE TITLE
JSON RPC batching

### ISSUE THREAD

**Issue by fracek** [xJonathanLEI/starknet-rs#190]
JSON RPC supports batching multiple requests into one (batching). The performance gain is quite high, for example it takes around 80-100 ms to fetch a single block, but ~200ms to fetch 25 with batching.

**Comment by xJonathanLEI** [comment]
Intersting. I didn't know this before. Will implement soon. Thanks!

**Comment by xJonathanLEI** [comment]
That would mean we need to make the method calls return some intermedia representation of the requests though, pretty much like we did with `Account::execute()`.

**Comment by fracek** [comment]
Yes, that's the best way to add batching.

Also notice a couple of things:

- The return values can be in any order (the server can process batches in parallel, which is cool), so need to use `id` to reorder them to the caller. Notice that _notifications_  don't produce responses (I don't think starknet rpc uses them so not an issue).
- Each individual batch request can fail, so the return value is something like `Vec<Result<Response>>`.
- The batch request itself can fail if its malformed.

**Comment by xJonathanLEI** [comment]
Yeah I mean then you have to do some kind of unwrap. Lemme have a think about how this can be best implemented. Will update this soon :)
