### ISSUE TITLE
`get_selector_from_name` argument lifetime

### ISSUE THREAD

**Issue by fracek** [xJonathanLEI/starknet-rs#192]
I'm using `get_selector_from_name` and, at the moment, the signature is the following:

```rust
pub fn get_selector_from_name(func_name: &str) -> Result<FieldElement, NonAsciiNameError>;
```

Which is equivalent to the following:

```rust
pub fn get_selector_from_name<'a>(func_name: &'a str) -> Result<FieldElement, NonAsciiNameError<'a>>;
```

This means that the function is unusable with the `?` operator since the borrowed argument will not live long enough (unless `func_name` is `'static`, but that's not usually the case).

**Workaround**

For now I just `map_err` to fix the lifetime requirements.

**Proposed solution**

Either have the error own `func_name` or just return the error type without `func_name`. I believe the latter approach is the most common, e.g. the [url crate](https://docs.rs/url/2.2.2/url/enum.ParseError.html) parse errors don't contain a copy or reference to the url that caused the error.

**Comment by xJonathanLEI** [comment]
Thanks for reporting the issue. I believe the latter solution is indeed better. We should not force cloning, and if the caller _really_ wants to have the function name in the error, he/she can always just wrap it.

**Comment by xJonathanLEI** [comment]
btw if `func_name` is static you might just want to use the `selector!()` macro, which computes the selector at compile time.

**Comment by fracek** [comment]
> Thanks for reporting the issue. I believe the latter solution is indeed better. We should not force cloning, and if the caller _really_ wants to have the function name in the error, he/she can always just wrap it.

Yes, I agree 100% with this.
