### ISSUE TITLE
Bug: FeeEstimate "amount" is now named "overall_fee" with StarkNet 0.9.1

### ISSUE THREAD

**Issue by ofux** [xJonathanLEI/starknet-rs#194]
A breaking change was introduced in StarkNet 0.9.1. 

See https://discord.com/channels/793094838509764618/988120113121214555/996026810930315385

> Hey team, as part of SN 0.9.1 upgrade, the response for estimate_fee is going to change to:
{"overall_fee":16968000079184,"unit":"wei","gas_price":1500000007,"gas_usage":1131}
Namely, amount => overall_fee is a breaking change.

**Comment by xJonathanLEI** [comment]
Didn't realize they released 0.9.1. Thanks for catching this!
