### ISSUE TITLE
Handle gateway response errors

### ISSUE THREAD

**Issue by fracek** [xJonathanLEI/starknet-rs#205]
I noticed that when the gateway returns a "too many requests" error, the error I get from the  `SequencerGatewayProvider` is a deserialization error (because the gateway returns an html page). I propose to add a `RateLimit` error to `ProviderError` to cover this case.

**Comment by xJonathanLEI** [comment]
Yeah makes sense to me, as long as the gateway returns a 429 status code properly.

**Comment by xJonathanLEI** [comment]
Our current test setup doesn't include HTTP status code or headers, making something like this hard to test as we can't just use the real gateway. So I will make changes to the test setup first before working on this.
