### ISSUE TITLE
Add examples for interfacing with `cairo-rs` (Cleopatra)

### ISSUE THREAD

**Issue by 0xSidius** [xJonathanLEI/starknet-rs#214]
@xJonathanLEI hi, i wonder if this will wrap `cairo-rs` and turn it into a Rust devnet, or is Cleopatra going to offer that API already?

**Comment by xJonathanLEI** [comment]
Hi. I'm not sure if I'm understanding what you want correctly, but `starknet-rs` isn't a sequencer implementation, but rather a client library which interfaces with such an implementation. It's indeed possible to wrap `cairo-rs` (or any other Cairo VM implementation) to create a devnet or even a full sequencer, but I doubt `starknet-rs` would be of any help.

**Comment by 0xSidius** [comment]
sorry, yes i am aware of the role of `starknet-rs` (i.e. `ethers` for starknet), I am wondering if `cairo-rs` is going to expose a devnet/node or if it can already do that, so that we won't have to rely on the Python `starknet-devnet` flask server

**Comment by xJonathanLEI** [comment]
Closing this as it looks like nothing can be done from our side.
