### ISSUE TITLE
Contract class hash equivalence with cairo-lang

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#216]
Currently, declaring or deploying a contract through this library results in a different class hash compared to the one generated from `cairo-lang`, presumbly because:

- the class hash itself it affected by a so-called `hinted_class_hash` field which is basically a StarkNet Keccak hash of the JSON representation of the contract; and
- at the same time, the sequencer takes field ordering as-is, meaning the exact same contract can have different JSON representations.

Obviously this hinted class hash is not validated by the StarkNet OS, and it doesn't _really_ hurt to have a different class hash from the official `cairo-lang` implementation, as long as this library can properly compute the hash locally so that it can prepare a v1 `deploy` transaction.

However, to avoid confusion, allow easier migration between SDKs, and to make sure we're indeed properly parsing every single bit of data from contract artifacts, it helps to output the same hash as `cairo-lang`. We should probably do just that.

**Comment by 0xSidius** [comment]
yes, for sure it should abide strictly to the `cairo-lang` convention for declaring. speaking of deployment, can you address this https://github.com/xJonathanLEI/starknet-rs/issues/214?
