### ISSUE TITLE
Run tests on OS X and Windows 

### ISSUE THREAD

**Issue by milancermak** [xJonathanLEI/starknet-rs#23]
Since we're building a library, we want to make sure it is available on all mainstream dev platforms. We're currently running the test pipeline only on Linux. Add OS X and Windows too.

**Comment by xJonathanLEI** [comment]
Much needed 👍

**Comment by xJonathanLEI** [comment]
I did something similar in [xJonathanLEI/starkware-crypto-rs#7](https://github.com/xJonathanLEI/starkware-crypto-rs/pull/7).
