### ISSUE TITLE
Any plans to support simulate transactions from account contracts?

### ISSUE THREAD

**Issue by Pet3ris** [xJonathanLEI/starknet-rs#252]
In addition to the current `estimate_fee` and `send` API, would be great to have a `simulate` endpoint that automatically signs for the transaction.

**Comment by xJonathanLEI** [comment]
Yep that sounds reasonable. Will work on this.

**Comment by xJonathanLEI** [comment]
I could just build on the current `Account` trait for this feature, but I'm not happy with how the trait itself looks right now. I'm working on a revamp of the `Account` trait before implementing this. The new interface should be a lot cleaner.
