### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by omarespejel** [xJonathanLEI/starknet-rs#268]
A brand new documentation would help the library. 

I am up to contributing to this (I am learning how to use the library).

WDYT?

**Comment by xJonathanLEI** [comment]
Hi thanks for the interest in the lib, but I'm afraid I don't quite understand what you're referring to as "new documentation". Do you mean something like #5, which is long overdue unfortunately.

**Comment by omarespejel** [comment]
Hey @xJonathanLEI! It is exactly what I was meaning. I will check #5 to contribute :)

**Comment by Tpkilgore197** [comment]
Contact the CEI of Face book for documentation ![image](https://github.com/xJonathanLEI/starknet-rs/assets/147801167/4487bb39-5a2a-40d6-97b4-593ebb43038f)![Uploading 324705560...]
