### ISSUE TITLE
JsonRpcClient `estimate_fee` method returns trait bound error

### ISSUE THREAD

**Issue by Eikix** [xJonathanLEI/starknet-rs#314]
Hi:),

I'm currently trying to estimate fees for a basic Kakarot transaction using the following code.

```rust

        let request = BroadcastedInvokeTransactionV1 {
            max_fee,
            signature,
            nonce,
            sender_address: starknet_address,
            calldata,
        };

        let starknet_estimated_fee = self
            .client
            .estimate_fee(request, &StarknetBlockId::Tag(BlockTag::Latest))
            .await?;
```

the `estimate_fee` function returns:

```
the trait bound `starknet::providers::jsonrpc::models::BroadcastedInvokeTransactionV1: std::convert::AsRef<starknet::providers::jsonrpc::models::BroadcastedTransaction>` is not satisfied
required for `&starknet::providers::jsonrpc::models::BroadcastedInvokeTransactionV1` to implement `std::convert::AsRef<starknet::providers::jsonrpc::models::BroadcastedTransaction>`
```

I tried passing the request as a reference with `.estimate_fee(&request, &StarknetBlockId::Tag(BlockTag::Latest))`, but it didn't change the error.
I'm not sure how to convert my request as_ref.

Thanks for your help

**Comment by xJonathanLEI** [comment]
Hi @Eikix. Could you clarify what it means for it to "return" the error? Do you mean a runtime error? Or do you mean it fails to compile with the error?

**Comment by Eikix** [comment]
> Hi @Eikix. Could you clarify what it means for it to "return" the error? Do you mean a runtime error? Or do you mean it fails to compile with the error?

My bad, it's a compile error

**Comment by xJonathanLEI** [comment]
You need to wrap it inside a `BroadcastedTransaction`. So it should be `BroadcastedTransaction::Invoke(BroadcastedInvokeTransaction::V1(request))`.

**Comment by Eikix** [comment]
Woopsie doopsie, thanks a lot for your help

**Comment by xJonathanLEI** [comment]
np :)
