### ISSUE TITLE
`/feeder_gateway/get_transaction` response deserialization failure

### ISSUE THREAD

**Issue by joeykraut** [xJonathanLEI/starknet-rs#333]
Looks like the data model for `TransactionInfo` [expects](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/transaction.rs#L133) a field `contract_address`, which is not a valid field in the response anymore on Goerli. It appears to have been replaced by `sender_address`:
- [Goerli Example](https://alpha4.starknet.io/feeder_gateway/get_transaction?transactionHash=0x2dc44b315aeb84e2a68367263d15d54ee229c1692c02f1d833ef870f7b6ce1a)

This API does not seem to have changed on mainnet yet; here's an example that still uses `contract_address`:
- [Mainnet Example](https://alpha-mainnet.starknet.io/feeder_gateway/get_transaction?transactionHash=0x1dc1bd0cfbc145d1583ec973fc99ca7b47cf4ace9eb469f405cbf3f7817f882)

This causes deserialization to fail in `SequencerGatewayProvider::get_transaction`

I'm happy to make a PR for this issue; not sure if you have a specific process you like to see for PRs @xJonathanLEI! Probably the best solution is to add a one-line alias, i.e.:
```rust
pub struct InvokeFunctionTransaction {
    #[serde_as(as = "UfeHex")]
    #[serde(alias = "sender_address")]
    pub contract_address: FieldElement,
    ...
}
```

**Comment by xJonathanLEI** [comment]
Hi @joeykraut. Thanks for reporting. PRs are welcome, but please note our approach to the difference between testnet & mainnet as discussed here: https://github.com/xJonathanLEI/starknet-rs/issues/27#issuecomment-1016195986

Basically, we expect any changes to eventually make their way to mainnet, and therefore do not attempt to support both at the same time in the same version. So it's fine for `master` to not function on mainnet.
