### ISSUE TITLE
Method not supported

### ISSUE THREAD

**Issue by culda** [xJonathanLEI/starknet-rs#390]
I'm having trouble using the Rust SDK to deploy an account due to `Provider(Other(MethodNotSupported))`

- I'm creating a `AccountDeployment` using `ArgentAccountFactory` as factory
- `deployment.address()` computes to `0x039bbbcfd5c88eff4ea1f68316cba1a2f5ac4a5297321b68ece4d4224d1af87b`
- `deployment.estimate_fee()` throws method not supported error

Not sure where I go wrong. Here is a code snippet

```
        let factory = ArgentAccountFactory::new(
            FieldElement::from_str(ARGENT_PROXY_HASH).unwrap(),
            FieldElement::from_str(ARGENT_IMPL_HASH).unwrap(),
            TESTNET,
            FieldElement::ZERO,
            signer.clone(),
            SequencerGatewayProvider::starknet_alpha_goerli_2(),
        )
        .await
        .unwrap();
        
        let deployment = AccountDeployment::new(salt, &factory);
        info!("Argent address: {}", address_str); // prints 0x039bbbcfd5c88eff4ea1f68316cba1a2f5ac4a5297321b68ece4d4224d1af87b
        let est_fee = deployment.estimate_fee().await.unwrap(); // throws MethodNotSupported error
```

**Comment by xJonathanLEI** [comment]
You're using an old version of `starknet-rs`.

**Comment by culda** [comment]
indeed, I was able to use a json rpc successfully. thanks

**Comment by xJonathanLEI** [comment]
```console
cargo update -p starknet
```
