### ISSUE TITLE
Unable to use starknet_ff in no_std

### ISSUE THREAD

**Issue by Th0rgal** [xJonathanLEI/starknet-rs#391]
Hello,

I am trying to use the `starknet_ff` crate in a no_std context (ledger app) but I'm encountering an issue with the `num-bigint` crate, which is a dependency of `starknet_ff`.

This issue occurs even when I disable default features:
```toml
starknet-ff = { version = "0.3.2", default-features = false }
```

Here are the building logs:
https://gist.github.com/Th0rgal/2ef2239a65bc317a2a896608f30ad39c

Is there a way to make `starknet_ff` compatible with no_std environments by either replacing or updating the `num-bigint` dependency or otherwise working around this issue?

Thank you for your help.

**Comment by xJonathanLEI** [comment]
`starknet-ff` _is_ `no_std` compatible. The crate you're having issue with m`num-bigint` is an optional dependency that's not pulled if you're indeed using the crate as you mentioned.

https://github.com/xJonathanLEI/starknet-rs/blob/a6cbfa3be71e9f42532c393632bdf18ccb01f88a/starknet-ff/Cargo.toml#L24

You should check your dependency tree.

**Comment by Th0rgal** [comment]
It's very odd, as soon as I remove the line it works. 

Here is the output dependency tree: https://gist.github.com/Th0rgal/5736be1b73387d0983c21d4971086422

**Comment by Th0rgal** [comment]
https://github.com/xJonathanLEI/starknet-rs/assets/41830259/7d3fb612-58fd-4772-a08a-d9b3bf3d82e4
