### ISSUE TITLE
`starknet-core` dependency `serde_json` arbitrary precision feature flag

### ISSUE THREAD

**Issue by fracek** [xJonathanLEI/starknet-rs#394]
The starknet-core crate has the [`serde_json` arbitrary precision feature flag enabled](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/Cargo.toml#L28).
This flag causes numbers to be encoded as the following object:

```json
{"$serde_json::private::Number": "123.45"}
```

Any library that depends on `starknet-core` will then use this encoding for numbers.
Since AFAIK the crate is not using this specific feature I believe it makes sense to drop the feature flag.

**Comment by xJonathanLEI** [comment]
This is a problem and the feature itself has caused issues but it's not true that the feature is not used. Specifically Cairo 0 contract artifacts require this to function.

Can you show me a minimal example where this is happening though? I've never encountered this specific issue myself. Thanks!

**Comment by fracek** [comment]
I created a [repro repo here](https://github.com/fracek/serde-json-issue). The issue only appears when serializing data with libraries that are not `serde_json` (in the repo `serde_yaml`, `serde_toml`,  and `serde_xml`).

**Comment by fracek** [comment]
The issue is with `LegacyIdentifier` right? I'm happy to work on a fix to remove the dependency on arbitrary precision.

**Comment by fracek** [comment]
Another option is to put the cairo0 stuff behind a feature flag and only set the arbitrary precision flag in that case.

**Comment by fracek** [comment]
Thanks! Really appreciate this.
