### ISSUE TITLE
`no_std` support for `starknet-core`

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#403]
Tracking issue for making the `starknet-core` crate `no_std`-compatible.

For reference, #306 made `starknet-crypto` `no_std`-compatible, and #308 added CI workflows for testing the compatibility.

**Comment by dbejarano820** [comment]
I can tackle

**Comment by dbejarano820** [comment]
Just as an update, this is a WIP

**Comment by exp-table** [comment]
LFG
