### ISSUE TITLE
Support declare transactions with version 0x0

### ISSUE THREAD

**Issue by fracek** [xJonathanLEI/starknet-rs#420]
I'm testing starknet-rs on the integration network and it looks like `DeclareTransaction` is missing the old V0 transactions. They still exist, for example [in this block](https://external.integration.starknet.io/feeder_gateway/get_block?blockNumber=165336).

According to the pathfinder team, [these transactions have the same representation as V1 transactions but with the version set to `0x0`](https://github.com/eqlabs/pathfinder#api-v021). I can see that the openapi spec is confusing with naming, but technically the version field can be 0x0 even in `DECLARE_TXN_V1`.

**Comment by xJonathanLEI** [comment]
Hmm I didn't know that. Do such transactions exist in any live network though? If it's only on integration there would be little point supporting it.

**Comment by fracek** [comment]
Yes, for example block 13 on testnet 2. https://alpha4-2.starknet.io/feeder_gateway/get_block?blockNumber=13
