### ISSUE TITLE
Support `starknet_simulateTransactions` in Provider trait for JsonRpcClient

### ISSUE THREAD

**Issue by Eikix** [xJonathanLEI/starknet-rs#437]
Hi there!

Afaik: since 0.3 Starknet JsonRpc Spec, RPC nodes support `starknet_simulateTransactions`. 
Afaik, starknet-rs only supports `starknet_simulateTransactions` for gateway and not jsonrpcclient?

Could we add support for it?

**Comment by xJonathanLEI** [comment]
This shouldn't be too difficult. We just need to modify `starknet-jsonrpc-codegen` to support this.

**Comment by xJonathanLEI** [comment]
Resolved by #481.
