### ISSUE TITLE
ContractFactory::deploy should return deployment address

### ISSUE THREAD

**Issue by FabijanC** [xJonathanLEI/starknet-rs#447]
To get the deployment address, currently one needs to either extract from the event emitted by the UDC, or manually calculate using the `get_udc_deployed_address` utility function. It would be better UX if this was available right away.

**Comment by xJonathanLEI** [comment]
Agree that this is a good feature, only one issue... We currently return an `Execution` upon calling `deploy()`, which is an `Account`-related struct that doesn't come with the context of contract deployment.

To allow extracting the contract address from the `deploy()` result, we need to add one more layer of abstraction here. Maybe change to return something new like `ContractDeployment`, which:

- wraps `Execution`
- implements `Execution` API to make it look like the `Execution` (so you can still call `.deploy().send()` like you do now)
- can be converted to `Execution` via the `Into` trait

Then we can implement additional methods on this type, including pre-computing the resulting contract address.
