### ISSUE TITLE
ECDSA signature validation doesn't comply common rules

### ISSUE THREAD

**Issue by satoshiotomakan** [xJonathanLEI/starknet-rs#449]
Is there any reason why `starknet-rs` needs that OR condition in `ecdsa::verify` for the "-x” case:
https://github.com/xJonathanLEI/starknet-rs/blob/832c6cdc36e5899cf2c82f8391a4dd409650eed1/starknet-crypto/src/ecdsa.rs#L161
while for ecdsa normally the check would be only
```rust
Ok((&zw_g + &rw_q).x == *r)
```

**Comment by xJonathanLEI** [comment]
A quick git blame shows that this line of code was originally added in #33.

**Comment by xJonathanLEI** [comment]
Upon further inspection, it looks like this line of code was directly ported from this:

https://github.com/starkware-libs/crypto-cpp/blob/78e3ed8dc7a0901fe6d62f4e99becc6e7936adfd/src/starkware/crypto/ecdsa.cc#L74

This line was in turn added in this commit: https://github.com/starkware-libs/crypto-cpp/commit/8217955bb71dc2718435ad9428277330177b98e5 by @MichaelRiabzev.

**Comment by xJonathanLEI** [comment]
Thanks to the pointer from @Mirko-von-Leipzig, I'm citing [this Wikipedia page](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm) (yeah I know, definitely very reputable source, what could possibly go wrong):

![image](https://github.com/xJonathanLEI/starknet-rs/assets/19556359/7df1b443-f7d0-4ceb-baee-b4a32e17154f)
(Screenshot as GitHub doesn't support LaTeX)

So I guess this would mean the current implementation is still correct? I'm open to removing the 2nd condition though, if not having it is the "standard" implementation.

Maybe @Oppen can also shed some light on this? Thanks in advance!

**Comment by script-money** [comment]
https://github.com/starkware-libs/cairo/blob/a5a0e7493733a3cb0923556e3d529fdfbc07ee80/corelib/src/ecdsa.cairo#L87
In my opinion, the 2nd condition should be preserved.

**Comment by xJonathanLEI** [comment]
Thanks @script-money. Based on this and Wikipedia I guess the current implementation is still correct and needs no change. I'm closing this issue now.
