### ISSUE TITLE
Poseidon hash instances are hardcoded

### ISSUE THREAD

**Issue by satoshiotomakan** [xJonathanLEI/starknet-rs#453]
The Poseidon hash original research paper (see Reference below) presents different possible instances of the Poseidon hash. The different instances proposed differs in the number of full rounds and partial rounds, or in the S-Box structure, or the structure of the Matrix used for the affine layer of a round. The parameters have an influence on the computation complexity of the hash function but more importantly on the level of security. The Starknet library hardcoded the parameters which means that only one instances of Poseidon of hash function is available when using the library.

The security level is 128 bits.

**Comment by xJonathanLEI** [comment]
Thanks for reporting. However, being robust on Poseidon instances is a non-goal for `starknet-rs`, which optimizes for ease of use instead.

For a robust and more Lego-like Poseidon library, use [poseidon-rs](https://github.com/keep-starknet-strange/poseidon-rs) instead.
