### ISSUE TITLE
False Negative: jsonrpc_estimate_fee test

### ISSUE THREAD

**Issue by wojciechos** [xJonathanLEI/starknet-rs#465]
In `starknet-providers->tests->jsonrpc.rs` the `jsonrpc_estimate_fee` test [sets max_fee to zero](https://github.com/xJonathanLEI/starknet-rs/blob/b575ef657fe677d17778d688c85fab7829affa98/starknet-providers/tests/jsonrpc.rs#L607) but then [asserts that all estimated fees should be greater than zero](https://github.com/xJonathanLEI/starknet-rs/blob/b575ef657fe677d17778d688c85fab7829affa98/starknet-providers/tests/jsonrpc.rs#L651).

```
max_fee: FieldElement::ZERO,
...
assert!(estimate.gas_consumed > 0);
assert!(estimate.overall_fee > 0);
```
**Issue:**
Setting max_fee as zero actually requires `estimate.overall_fee` and `estimate.gas_consumed` to be zero, not bigger than zero.

**Comment by xJonathanLEI** [comment]
This is actually not true. The zero value here merely acts as a placeholder. You're literally asking the node what the `max_fee` field should be, after all. The `max_fee` field technically shouldn't even exist in this request, but is required by the specs so here we are.

**Comment by xJonathanLEI** [comment]
As a server, you can't expect the client to provide a meaningful `max_fee` value when they're literally asking you for a `max_fee` value. Closing this optimistically. Feel free to re-open though.

**Comment by omerfirmak** [comment]
This is actually a limitation on `blockifier`. It respects the max_fee field regardless of the execution context.
