### ISSUE TITLE
Entry point offset could be deserialized from numeric value

### ISSUE THREAD

**Issue by FabijanC** [xJonathanLEI/starknet-rs#490]
As requested by @amanusk, here is a slightly improved request already posted [on Telegram](https://t.me/starknet_rs/5002).

Lately a discrepancy has been noticed in the way different services treat the format of offset of members of `entry_points_by_type` in the body of `DECLARE_TXN_V1` (i.e. declaring of deprecated Cairo 0 contracts):

- The specification states that offset is NUM_AS_HEX, i.e. a hex string ([spec link](https://github.com/starkware-libs/starknet-specs/blob/v0.5.0/api/starknet_api_openrpc.json#L2967))
- However this is not in sync with compilation artifacts since cairo-lang v0.10.x, when it switched from hex string to a numeric literal.
- starknet.rs (i.e. its crate starknet-core) is following the specification:
https://github.com/xJonathanLEI/starknet-rs/blob/1d2eb07ff355bd787c143ac1aca633a6c636cfe9/starknet-core/src/types/codegen.rs#L804
- starknet-devnet-rs is relying on starknet-core, so transitively following the specification
- Pathfinder and starknet.js are treating this offset as a number (as well as hex string).

I'm speaking on behalf of starknet-devnet-rs, where many users have been reporting that they can no longer declare Cairo 0 contracts as they used to with starknet-devnet, and it's because the offset format in their request is wrong.  As much as I would like everyone to just follow the specification, IMO it would be the simplest solution to just tweak the offset serde directive in starknet.rs to allow both numeric and hex string values.

There is a PR (https://github.com/starkware-libs/starknet-specs/pull/152) for this in the starknet-specs repo, and it's been reported on [Slack](https://spaceshard.slack.com/archives/C03QN20522D/p1698404739235799) in the starknet-json-rpc channel.

Let me know what you think about this intervention :pray:

**Comment by xJonathanLEI** [comment]
Hmm sorry I somehow missed this issue.

It's fixed and released in #491. So I'm closing this issue now.
