### ISSUE TITLE
Add support for `flat` event

### ISSUE THREAD

**Issue by milancermak** [xJonathanLEI/starknet-rs#499]
Cairo has a new [flat event](https://github.com/starkware-libs/cairo/pull/4112). The rationale is [described here](community.starknet.io/t/cairo-v2-3-0-release-candidate/101137).

In the code it looks [something like this](https://github.com/OpenZeppelin/cairo-contracts/blob/4eafccf107f98d975b20cbb6544b2a998e5f403f/src/tests/mocks/ownable_mocks.cairo#L24).

In the ABI, it's something like this (note this example is from a different contract):

```json
{
            "type": "event",
            "name": "twostep::one::one::Event",
            "kind": "enum",
            "variants": [
                {
                    "name": "OwnableEvent",
                    "type": "openzeppelin::access::ownable::ownable::OwnableComponent::Event",
                    "kind": "flat"
                },
                {
                    "name": "UpgradeableEvent",
                    "type": "openzeppelin::upgrades::upgradeable::UpgradeableComponent::Event",
                    "kind": "flat"
                }
            ]
        }
```

This isn't currently supported by the lib.

Found out while trying to declare a contract with a flat event using starkli, which failed with `Error: failed to parse contract artifact`.

**Comment by xJonathanLEI** [comment]
Thanks for the heads up! Fixing it today.

**Comment by milancermak** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmw4bDF6OWZid3ZucWh3ZW5xaXQ0Yng4ODhvdW90bWY1dWppejFrNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/11llTu9bwVT2AE/giphy.gif)
