### ISSUE TITLE
Full documentation coverage on public items

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#5]
There's currently very little documentation. We need to:

- [x] achieve full doc coverage on all public items on all crates
- [x] add `#![deny(missing_docs)]` to all crates to enforce documentation

**Comment by omarespejel** [comment]
I would love to work on this. Any particular pattern/format you would want to follow for the documentation?

**Comment by xJonathanLEI** [comment]
Thanks @omarespejel! I guess it's best to follow existing items that already have some docs. e.g.

https://github.com/xJonathanLEI/starknet-rs/blob/f7cc49ea99aaccbfb2465fe8fb665bdff21da044/starknet-ff/src/lib.rs#L147-L156

**Comment by xJonathanLEI** [comment]
Basic documentation now exists for all crates. The docs are by no means extensive. In most cases they're just basic description of what the type/method does, without giving code examples. Nevertheless, this issue should now be considered completed.
