### ISSUE TITLE
Support JSON-RPC v0.5

### ISSUE THREAD

**Issue by fracek** [xJonathanLEI/starknet-rs#502]
With the imminent release of the JSON-RPC spec v0.6, nodes will remove JSON-RPC v0.4 (they have a policy of keeping the 2 most recent specs). Do you plan to add JSON-RPC 0.5 soon? Can I help with it?

**Comment by xJonathanLEI** [comment]
Oh it's actually already done. It's on the branch `dev/jsonrpc_0_5_0`.

**Comment by fracek** [comment]
Cool, thank you!
