### ISSUE TITLE
Support RPC 0.6.0

### ISSUE THREAD

**Issue by THenry14** [xJonathanLEI/starknet-rs#515]
Hi, I didn't see an open issue for rpc 0.6.0 support, so took the liberty to open one.
The release was yesterday (https://github.com/starkware-libs/starknet-specs/releases/tag/v0.6.0), and it should hit testnet in a few days (12.12). It would be cool to support this as soon as possible. thanks.

**Comment by xJonathanLEI** [comment]
It's being worked on.

**Comment by xJonathanLEI** [comment]
Finished in #523.
