### ISSUE TITLE
No reference to `result.transactions[0].sender_address` property in `starknet_getBlockWithTxs` method.

### ISSUE THREAD

**Issue by berzanorg** [xJonathanLEI/starknet-rs#560]
I noticed that each item in `starknet_getBlockWithTxs` method's return value's `transactions` property has an optional property called `sender_address`. But I haven't been able to find a reference to that property in the source code of the `starknet-rs` crate.

I wonder if the methods of the RPC provider I am using (it's v0.6) is outdated or something.

If not the return types of RPC methods might need to be updated in the `starknet-rs` crate.

`BlockWithTxs` struct: https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/codegen.rs#L115C12-L115C25
`Transaction` enum: https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/mod.rs#L181

For example you can make the request below to a Starknet Testnet RPC provider and notice that some of the items in the `result.transactions` property have `sender_address` property.

```json
{
    "jsonrpc": "2.0",
    "method": "starknet_getBlockWithTxs",
    "params": [
        {
            "block_number": 955848
        }
    ],
    "id": 1
}
```

**Comment by xJonathanLEI** [comment]
`sender_address` is indeed available, but you're probably trying to access it from the umbrella `Transaction` type, which is an enum type that contains multiple variants.

Only `DECLARE` and `INVOKE` transactions have the `sender_address` field. You will need to match down to these variants to be able to access them.
