### ISSUE TITLE
Divide by zero panics in `bigint_mul_mod_floor` and `mul_mod_floor` if modulus set to 0

### ISSUE THREAD

**Issue by pventuzelo** [xJonathanLEI/starknet-rs#584]
Hey Jonathan,

During code review, we (@fuzzinglabs) found a case making starknet-rs crash. The crash occurs when trying to call the `bigint_mul_mod_floor` function in  `starknet-crypto`. If the `modulus` parameter of the function is set to 0, then calling the `bigint_mul_mod_floor` function will raise an attempt to divide by zero in the `num-bigint` dependency leading to a crash.

This vulnerability might lead to DoS of the libraries/projects using starknet-rs as 3rd party if they are not checking the modulus value before calling the function.

As a best practice, we will suggest that starknet-rs should make the verification to prevent any crashes.

## Vulnerability Details

- **Affected Component:** https://github.com/xJonathanLEI/starknet-rs/tree/f33d3522eca61f6d9f7288527e8b048e84deeefd
    - [bigint_mul_mod_floor](https://github.com/xJonathanLEI/starknet-rs/blob/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto/src/fe_utils.rs#L29) function in the [fe_utils.rs](https://github.com/xJonathanLEI/starknet-rs/blob/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto/src/fe_utils.rs) file in the [starknet-crypto](https://github.com/xJonathanLEI/starknet-rs/tree/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto) crate
    - [mul_mod_floor](https://github.com/xJonathanLEI/starknet-rs/blob/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto/src/fe_utils.rs#L20) function in the [fe_utils.rs](https://github.com/xJonathanLEI/starknet-rs/blob/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto/src/fe_utils.rs) file in the [starknet-crypto](https://github.com/xJonathanLEI/starknet-rs/tree/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto) crate

## Steps to Reproduce

**main.rs:**

```rust
use num_bigint::{BigInt, Sign};
use starknet_core::types::FieldElement;
use starknet_crypto::fe_utils::bigint_mul_mod_floor;

fn main() {
    let _ = bigint_mul_mod_floor(BigInt::new(Sign::Plus, vec![]), &FieldElement::from_mont([0, 0, 0, 0]), &FieldElement::from_mont([0, 0, 0, 0]));
}
```

## Root Cause Analysis

```bash
thread 'main' panicked at /home/fuzzinglabs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.4/src/biguint/division.rs:168:9:
attempt to divide by zero
```

Related codes: 

`fe_utils.rs` code:  the `bigint_mul_mod_floor` function code that leads to a crash:

https://github.com/xJonathanLEI/starknet-rs/blob/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto/src/fe_utils.rs#L37

`fe_utils.rs` code: the `mul_mod_floor` function code in `fe_utils.rs` that uses the `bigint_mul_mod_floor` function from the `fe_utils.rs`:

https://github.com/xJonathanLEI/starknet-rs/blob/f33d3522eca61f6d9f7288527e8b048e84deeefd/starknet-crypto/src/fe_utils.rs#L26

Reproducer using the `mul_mod_floor` function:

```bash
use starknet_core::types::FieldElement;
use starknet_crypto::fe_utils::mul_mod_floor;

fn main() {
    let _ = mul_mod_floor(&FieldElement::from_mont([0, 0, 0, 0]), &FieldElement::from_mont([0, 0, 0, 0]), &FieldElement::from_mont([0, 0, 0, 0]));
}
```

## Detailed Behavior **(RUST_BACKTRACE=1)**

```
thread 'main' panicked at /home/fuzzinglabs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.4/src/biguint/division.rs:168:9:
attempt to divide by zero
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:686:12
   1: num_bigint::biguint::division::div_rem_ref
             at /home/fuzzinglabs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.4/src/biguint/division.rs:168:9
   2: <num_bigint::biguint::BigUint as num_integer::Integer>::mod_floor
             at /home/fuzzinglabs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.4/src/biguint.rs:197:22
   3: <num_bigint::bigint::BigInt as num_integer::Integer>::mod_floor
             at /home/fuzzinglabs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.4/src/bigint.rs:388:20
   4: starknet_crypto::fe_utils::bigint_mul_mod_floor
             at /home/fuzzinglabs/Downloads/starknet-rs/starknet-crypto/src/fe_utils.rs:37:18
   5: fuzzing::main
             at ./fuzzpart/src/main.rs:7:13
   6: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
```

**Comment by xJonathanLEI** [comment]
Thanks for reporting! Lemme look into this and work on a fix.

**Comment by xJonathanLEI** [comment]
Hmmm wait a second. The `fe_utils` module is private and is not accessible by external crates. I can't make sense of the reproducer... how is it able to import that module at all?

As for internal use, all call sites of the 2 mentioned functions supply `EC_ORDER` as `modulus`, which is guaranteed to be non-zero.

So I don't really see this being a real vulnerability?

**Comment by pventuzelo** [comment]
Oh my bad, I reproduced the bug on a project that forked the repo and got `fe_utils` in public.
Thanks,
