### ISSUE TITLE
Add more clippy lint rules

### ISSUE THREAD

**Issue by tcoratger** [xJonathanLEI/starknet-rs#596]
In order for the codebase to be more Rust idiomatic and to improve some part/performance, we could enforce more clippy lint rules at a root level.

See for example what is done here:

https://github.com/paradigmxyz/reth/blob/56859b417226b0b799484f4251cfe04c1d848958/Cargo.toml#L113-L186

Generally speaking, there are certain rules that are painful to have or maintain, but some from the list mentioned above are extremely useful to have on a repository to maintain a high level of code quality and maintainability.

**Comment by aniketpr01** [comment]
@tcoratger Can i take this

**Comment by tcoratger** [comment]
> @tcoratger Can i take this

Assigned
