### ISSUE TITLE
replace Poseidon implementation by `types-rs`

### ISSUE THREAD

**Issue by tcoratger** [xJonathanLEI/starknet-rs#608]
The following Poseidon implementation

https://github.com/xJonathanLEI/starknet-rs/blob/4dbc1692d4f295de803484181e07803201528922/starknet-crypto/src/poseidon_hash.rs

should be replaced by the dedicated `type-rs` provided implementation:

https://github.com/starknet-io/types-rs/blob/main/crates/starknet-types-core/src/hash/poseidon.rs

**Comment by thetheveloper** [comment]
We would like to be assigned to this issue

cc @tcoratger @xJonathanLEI
