### ISSUE TITLE
replace Pedersen implementation by `type-rs`

### ISSUE THREAD

**Issue by tcoratger** [xJonathanLEI/starknet-rs#609]
The following Pedersen implementation

https://github.com/xJonathanLEI/starknet-rs/blob/4dbc1692d4f295de803484181e07803201528922/starknet-crypto/src/pedersen_hash.rs

should be replaced by the dedicated `type-rs` provided implementation:

https://github.com/starknet-io/types-rs/blob/main/crates/starknet-types-core/src/hash/pedersen.rs

**Comment by thetheveloper** [comment]
We would like to be assigned to this issue

cc @tcoratger @xJonathanLEI

**Comment by tcoratger** [comment]
> We would like to be assigned to this issue
> 
> cc @tcoratger @xJonathanLEI

Assigned
