### ISSUE TITLE
Match response object type names with `cairo-lang`

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#64]
With the release of StarkNet `v0.7.1`, I noticed that a new file [response_objects.py](https://github.com/starkware-libs/cairo-lang/blob/ed6cf8d6cec50a6ad95fa36d1eb4a7f48538019e/src/starkware/starknet/services/api/feeder_gateway/response_objects.py) has been added to [cairo-lang](https://github.com/starkware-libs/cairo-lang) which contains gateway response object type definitions. While they're still using `JsonObject` for most requests, some of them are now typed and thus have official names.

We should probably update our code to match with their names, for the sake of making it easier for people familiar with [cairo-lang](https://github.com/starkware-libs/cairo-lang) to start using our library.

**Comment by xJonathanLEI** [comment]
This probably means some of the types introduced by #60 will need to be changed again. @milancermak what do you think?

**Comment by milancermak** [comment]
Well spotted! If you like, I can have a look at what should be done.

**Comment by xJonathanLEI** [comment]
Thank you! Much appreciated!
