### ISSUE TITLE
Incompatibility between `CompiledClass` and compiler's `CasmContractClass`

### ISSUE THREAD

**Issue by integraledelebesgue** [xJonathanLEI/starknet-rs#649]
# Issue
A `CompiledClass` structure from `starknet-rs::crates::starknet-core::src::types::contract::mod` and `CasmContractClass` from `cairo-compiler::crates::cairo-lang-starknet-classes::src::casm_contract_class` have one divergence: the `bytecode_segment_lengths` field.

That difference results in failing deserialization of compiler's output in `starknet-foundry`'s `sncast` declaration.

# Reproduction:
1. Obtain `starknet-foundry` [source code](https://github.com/foundry-rs/starknet-foundry)
2. Setup environment following the [instruction](https://foundry-rs.github.io/starknet-foundry/development/environment-setup.html)
3. Launch test: `cargo test -p sncast e2e::declare::test_happy_case_specify_package` on a `master` branch
4. Observe a fail

The reason this test fails is unsucceeded deserialization of a CASM artifact into the `CompiledClass` in `starknet-foundry::crates::sncast::src::starknet_commands::declare : 84`.
We are deserializing a trivial contract: [here](https://github.com/foundry-rs/starknet-foundry/blob/master/crates/sncast/tests/data/contracts/multiple_packages/src/lib.cairo). Compiler writes `bytecode_segment_lengths = 0`, while `CompiledClass` deserializer expects a list of integers/nested lists.

# Source code:
1. `starknet-rs`:
```rust
pub struct CompiledClass {
    // [..]
    pub bytecode_segment_lengths: Vec<IntOrList>,
}

pub enum IntOrList {
    Int(u64),
    List(Vec<IntOrList>),
}
```

2. `cairo-compiler`:
```rust
pub struct CasmContractClass {
    /// [..]
    pub bytecode_segment_lengths: Option<NestedIntList>
}

pub enum NestedIntList {
    Leaf(usize),
    Node(Vec<NestedIntList>),
}
```

**Comment by xJonathanLEI** [comment]
Thanks for reporting! Can reproduce it with any trivial Cairo contract. Just added the test case. Working on fixing it now.
