### ISSUE TITLE
Add support for full node JSON-RPC

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#77]
[pathfinder](https://github.com/eqlabs/pathfinder) just made the [first public release](https://github.com/eqlabs/pathfinder/releases/tag/v0.1.0-alpha). We need to add support for the JSON-RPC APIs formally defined [here](https://github.com/starkware-libs/starknet-specs).

_Update: I will consider the support to be done once the list of methods implemented by `pathfinder` is covered, since we don't really have a good way to test the others._

_Note: While `starknet_getCode` is implemented by `pathfinder`, we will not support this method since it's already been removed from the spec._

- [x] starknet_getBlockByHash
- [x] starknet_getBlockByNumber
- [x] starknet_getStorageAt
- [x] starknet_getTransactionByHash
- [x] starknet_getTransactionByBlockHashAndIndex
- [x] starknet_getTransactionByBlockNumberAndIndex
- [x] starknet_getTransactionReceipt
- [x] starknet_getBlockTransactionCountByHash
- [x] starknet_getBlockTransactionCountByNumber
- [x] starknet_call
- [x] starknet_blockNumber
- [x] starknet_chainId
- [x] starknet_syncing
- [x] starknet_getEvents
- [x] starknet_addInvokeTransaction
- [x] starknet_addDeployTransaction
- [x] starknet_addDeclareTransaction

**Comment by xJonathanLEI** [comment]
It looks like the [current specification](https://github.com/starkware-libs/starknet-specs/blob/20e56ea6435bc1fd60be0e24686323c32b33e8a5/api/starknet_api_openrpc.json) only contains read-only methods. As a result, there seems to be no way to submit transactions other than talking to the sequencer directly through the gateway.

This makes things kinda awkward, as we can't just use the JSON-RPC client as a `Provider` implementation. It can't send out transactions after all.

**Comment by xJonathanLEI** [comment]
OK so now we have a problem that's pretty much unique to StarkNet. We have 2 officially supported ways of talking to the network: either through the sequencer gateway APIs or through full node JSON-RPC. What's quite annoying is that their functionalities are not identical, so it's not trivial to properly define a generic `Provider` trait to cover them both.

I _do_ expect the functionalities of both to converge over time (e.g. the ability to send transactions to be added to JSON-RPC) and on top of that, the sequencer gateway will be deprecated in favor of JSON-RPC (i.e. the decentralization phase), at which point we can simply define `Provider` based on the JSON-RPC specs.

But right now, the JSON-RPC isn't even on par with the gateway in terms of functionalities, and is missing arguably the most important method for it to be useful. Obviously we can't just change `Provider` to match the JSON-RPC specs at this point because of that.

So how do we handle the support for JSON-RPC clients? Obviously we'll be adding something like `JsonRpcClient`, but should this type implement the `Provider` trait at all? We can either:

- leave this type alone and not implement `Provider` until it's at least on par with the gateway APIs; or
- implement `Provider` but throws on not-yet supported methods; to use JSON-RPC-only methods (e.g. `starknet_chainId`) users will have to use the concrete type directly instead of going through the trait.

Personally I prefer the former option. @milancermak WDYT?

**Comment by xJonathanLEI** [comment]
Also, I haven't started playing around with the JSON-RPC yet, but I guess the JSON-RPC response data structures will be different from those coming from the sequencer, in which case it will bring even more complications, but let's deal with the trait thing first :))

**Comment by milancermak** [comment]
I also prefer the first option. 

I actually wonder if the two specs will eventually converge. Maybe the feeder gateway will just be deprecated and lost to history and the full node API will (have to) be used everywhere.

**Comment by milancermak** [comment]
Interesting point in the spec - [felts](https://github.com/starkware-libs/starknet-specs/blob/20e56ea6435bc1fd60be0e24686323c32b33e8a5/api/starknet_api_openrpc.json#L778-L784) will be represented as hex strings everywhere. Hooray for consistency :)

**Comment by xJonathanLEI** [comment]
Oh nice finally lol

**Comment by xJonathanLEI** [comment]
Starting to work on this as full nodes are now the preferred way of querying data since the sequencer APIs are quite overloaded all the time.

**Comment by xJonathanLEI** [comment]
Looks like the JSON-RPC spec now indeed [contains the broadcast methods](https://github.com/starkware-libs/starknet-specs/blob/bcce12075ef4cde19fc62b47ed2162292e0ed70d/api/starknet_write_api.json#L11).

**Comment by milancermak** [comment]
From my side, I don't mind eventually having a breaking release that updates to the JSON-RPC API, I expected it anyways. If you want to build the bridging methods, that's fine, but might not be worth the effort, especially if you're thinking of doing it continuously considering the inconsistencies in the API between releases.
