### ISSUE TITLE
Duplicate InvokeFunction types

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/starknet-rs#88]
Looks like `starknet_core::types::transaction_request::InvokeFunctionTransaction` is literally the same as  `starknet_core::types::call_contract::CallContractResult`. We should remove the latter.

**Comment by milancermak** [comment]
Do you mean `starknet_core::types::call_contract::InvokeFunction`, not `starknet_core::types::call_contract::CallContractResult`?

**Comment by xJonathanLEI** [comment]
Yeah was a typo 😂😂
