### ISSUE TITLE
Refactor Account Deployment

### ISSUE THREAD

**Issue by abigger87** [xJonathanLEI/starknet-rs#96]
Deploying accounts should be refactored and accessible behind some Account Factory Trait.

**Comment by xJonathanLEI** [comment]
I think this will be best structured as:

- an `AccountFactory` (as always, naming not final) trait; and
- an additional feature-gated crate like `starknet-account-impls` that contains the actual account contracts.

**Comment by xJonathanLEI** [comment]
A lot has changed regarding StarkNet contract deployment (including account deployment), so I'm planning to revamp the interface, which should take care of this. See #232.
